// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBshlezN409x7y2cjEPlgK4RGQAmVG66aI',
    appId: '1:69949065857:web:6d4224b3ce56ba76a89b80',
    messagingSenderId: '69949065857',
    projectId: 'krabetjihad',
    authDomain: 'krabetjihad.firebaseapp.com',
    storageBucket: 'krabetjihad.appspot.com',
    measurementId: 'G-D45QJB3Q6V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcC9ZqpndYK92qc4NGzrD6xy4AGb3wb-U',
    appId: '1:69949065857:android:62314053da05bb5aa89b80',
    messagingSenderId: '69949065857',
    projectId: 'krabetjihad',
    storageBucket: 'krabetjihad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_r-_QeZ7-0r5vuaV6EnsnivZlwXP33Ck',
    appId: '1:69949065857:ios:35c7f7528fb3bb2fa89b80',
    messagingSenderId: '69949065857',
    projectId: 'krabetjihad',
    storageBucket: 'krabetjihad.appspot.com',
    iosClientId: '69949065857-kthb1dv66k5mianoacs85kfbu4i17u7k.apps.googleusercontent.com',
    iosBundleId: 'com.example.krabetjihad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_r-_QeZ7-0r5vuaV6EnsnivZlwXP33Ck',
    appId: '1:69949065857:ios:cbd345b0d4a46e35a89b80',
    messagingSenderId: '69949065857',
    projectId: 'krabetjihad',
    storageBucket: 'krabetjihad.appspot.com',
    iosClientId: '69949065857-mjj928sbh9ojh9ke5u3eo6mi4a2maud2.apps.googleusercontent.com',
    iosBundleId: 'com.example.krabetjihad.RunnerTests',
  );
}
